### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by ghost** [SayakaIsBaka/fls-rich-presence#1]
I have the issue,

Line: 3
Char 1:
Error: The requested operation requires elevation.

Code: 800702E4
Source: WshShell.Exec

**Comment by SayakaIsBaka** [comment]
How are you running the script? Can you give me a bit more details please?

**Comment by SayakaIsBaka** [comment]
You have to run the script as admin, I'll make a second script that will be able to run it as admin
